# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('pacientes', '0002_rename_enfermeiro_paciente_responsavel'),
        ('unidades_de_saude', '0003_unidadedesaude_unidades_de_removid_8832d8_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['data'], name='entradas_en_data_c7f945_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['paciente', 'removido_em'], name='entradas_en_pacient_4937cf_idx'),
        ),
    ]
