# Generated by Django 5.1.5 on 2025-01-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_entrada_entradas_en_data_c7f945_idx_and_more'),
        ('unidades_de_saude', '0003_unidadedesaude_unidades_de_removid_8832d8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='unidade_de_saude_de_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades_de_saude.unidadedesaude', verbose_name='Unidade de Saúde de Origem'),
        ),
    ]
