# Generated by Django 5.1.5 on 2025-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_alter_entrada_removido_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='hora',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
