# Generated by Django 5.1.5 on 2025-01-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leitos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('tipos_de_saida', '0001_initial'),
        ('unidades_de_saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('removido_em', models.DateTimeField(null=True, verbose_name='Removido em')),
                ('leito_de_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leitos.leito', verbose_name='Leito de Origem')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
                ('tipo_de_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_de_saida.tipodesaida', verbose_name='Tipo de Saída')),
                ('unidade_de_saude_de_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades_de_saude.unidadedesaude', verbose_name='Unidade de Saúde de Destino')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
        ),
    ]
