# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('pacientes', '0003_alter_paciente_data_de_nascimento_and_more'),
        ('saidas', '0001_initial'),
        ('tipos_de_saida', '0003_tipodesaida_tipos_de_sa_removid_913673_idx'),
        ('unidades_de_saude', '0003_unidadedesaude_unidades_de_removid_8832d8_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['removido_em'], name='saidas_said_removid_b91829_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['data', 'removido_em'], name='saidas_said_data_026762_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['paciente', 'removido_em'], name='saidas_said_pacient_5925eb_idx'),
        ),
    ]
