# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgias', '0001_initial'),
        ('especialidades', '0003_especialidade_especialida_removid_441019_idx'),
        ('pacientes', '0002_rename_enfermeiro_paciente_responsavel'),
        ('setores', '0003_setor_setores_set_removid_d33d62_idx'),
        ('tipos_de_cirurgia', '0003_tipodecirurgia_tipos_de_ci_removid_914369_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cirurgia',
            index=models.Index(fields=['removido_em'], name='cirurgias_c_removid_745fae_idx'),
        ),
        migrations.AddIndex(
            model_name='cirurgia',
            index=models.Index(fields=['paciente', 'removido_em'], name='cirurgias_c_pacient_c6f930_idx'),
        ),
    ]
