# Generated by Django 5.1.5 on 2025-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgias', '0002_cirurgia_cirurgias_c_removid_745fae_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirurgia',
            name='hora',
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
