# Generated by Django 5.1.5 on 2025-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirurgias', '0003_remove_cirurgia_hora_alter_cirurgia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
    ]
