# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_de_cirurgia', '0002_alter_tipodecirurgia_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tipodecirurgia',
            index=models.Index(fields=['removido_em'], name='tipos_de_ci_removid_914369_idx'),
        ),
    ]
