# Generated by Django 5.1.5 on 2025-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_de_leito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusdeleito',
            options={'verbose_name': 'Status de Leito', 'verbose_name_plural': 'Status de Leito'},
        ),
        migrations.AlterField(
            model_name='statusdeleito',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
    ]
