# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_de_leito', '0002_alter_statusdeleito_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statusdeleito',
            index=models.Index(fields=['removido_em'], name='status_de_l_removid_a0a760_idx'),
        ),
    ]
