# Generated by Django 5.1.5 on 2025-01-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leitos', '0002_alter_leito_codigo_sus_alter_leito_removido_em_and_more'),
        ('pacientes', '0002_rename_enfermeiro_paciente_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDeOcupacaoLeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True, verbose_name='Ocorrido em')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_de_ocupacao_de_leito', to='leitos.leito', verbose_name='Leito')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Histórico de Ocupação de Leito',
                'verbose_name_plural': 'Históricos de Ocupação de Leito',
            },
        ),
    ]
