# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_de_ocupacao_de_leito', '0002_historicodeocupacaodeleito_and_more'),
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('pacientes', '0002_rename_enfermeiro_paciente_responsavel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicodeocupacaodeleito',
            index=models.Index(fields=['leito'], name='historico_d_leito_i_9e5de2_idx'),
        ),
    ]
