# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_alter_setor_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='setor',
            index=models.Index(fields=['removido_em'], name='setores_set_removid_d33d62_idx'),
        ),
    ]
