# Generated by Django 5.1.5 on 2025-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=7, unique=True, verbose_name='Cor')),
                ('nome', models.CharField(max_length=128, unique=True, verbose_name='Nome')),
                ('removido_em', models.DateTimeField(null=True, verbose_name='Removido em')),
            ],
            options={
                'verbose_name': 'Status de Paciente',
                'verbose_name_plural': 'Status de Paciente',
            },
        ),
    ]
