# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_de_paciente', '0002_alter_statusdepaciente_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statusdepaciente',
            index=models.Index(fields=['removido_em'], name='status_de_p_removid_3470d6_idx'),
        ),
    ]
