# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_de_vacuo', '0002_alter_tipodevacuo_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tipodevacuo',
            index=models.Index(fields=['removido_em'], name='tipos_de_va_removid_6a4b9d_idx'),
        ),
    ]
