# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas_de_precaucao', '0002_alter_medidadeprecaucao_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medidadeprecaucao',
            index=models.Index(fields=['removido_em'], name='medidas_de__removid_b9d74a_idx'),
        ),
    ]
