# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidades_etnias', '0002_alter_nacionalidadeetnia_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nacionalidadeetnia',
            index=models.Index(fields=['removido_em'], name='nacionalida_removid_d22a3c_idx'),
        ),
    ]
