# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_de_saida', '0002_alter_tipodesaida_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tipodesaida',
            index=models.Index(fields=['removido_em'], name='tipos_de_sa_removid_913673_idx'),
        ),
    ]
