# Generated by Django 5.1.5 on 2025-01-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        ('generos', '0001_initial'),
        ('leitos', '0001_initial'),
        ('medidas_de_precaucao', '0001_initial'),
        ('nacionalidades_etnias', '0001_initial'),
        ('portas_de_entrada', '0001_initial'),
        ('status_de_paciente', '0001_initial'),
        ('tipos_de_cirurgia', '0001_initial'),
        ('tipos_de_o2', '0001_initial'),
        ('tipos_de_vacuo', '0001_initial'),
        ('unidades_de_saude', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('nome_social', models.CharField(max_length=128, null=True, verbose_name='Nome Social')),
                ('data_de_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('data_de_internacao', models.DateField(verbose_name='Data de Internação')),
                ('hora_de_internacao', models.TimeField(verbose_name='Hora de Internação')),
                ('data_de_internacao_no_setor', models.DateField(verbose_name='Data de Internação no Setor')),
                ('hora_de_internacao_no_setor', models.TimeField(verbose_name='Hora de Internação no Setor')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('diagnostico', models.TextField(max_length=2048, verbose_name='Diagnóstico')),
                ('justificativas_pendencias', models.TextField(max_length=2048, verbose_name='Justificativas de Pendências')),
                ('problemas_durante_transferencias', models.TextField(max_length=2048, null=True, verbose_name='Problemas Durante Transferências')),
                ('gestante', models.BooleanField(default=False, verbose_name='Gestante')),
                ('veio_de_ambulancia', models.BooleanField(default=False, verbose_name='Veio de Ambulância')),
                ('precisa_de_cirurgia', models.BooleanField(default=False, verbose_name='Precisa de Cirurgia')),
                ('precisa_de_o2', models.BooleanField(default=False, verbose_name='Precisa de O2')),
                ('precisa_de_vacuo', models.BooleanField(default=False, verbose_name='Precisa de Vácuo')),
                ('removido_em', models.DateTimeField(null=True, verbose_name='Removido em')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='Profissional de Saúde Responsável')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='generos.genero', verbose_name='Gênero')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leitos.leito', verbose_name='Leito')),
                ('medida_de_precaucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medidas_de_precaucao.medidadeprecaucao', verbose_name='Medida de Precaução')),
                ('nacionalidade_etnia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nacionalidades_etnias.nacionalidadeetnia', verbose_name='Nacionalidade/Etnia')),
                ('porta_de_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas_de_entrada.portadeentrada', verbose_name='Porta de Entrada')),
                ('status_de_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status_de_paciente.statusdepaciente', verbose_name='Status do Paciente')),
                ('tipo_de_cirurgia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_cirurgia.tipodecirurgia', verbose_name='Tipo de Cirurgia')),
                ('tipo_de_o2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_o2.tipodeo2', verbose_name='Tipo de O2')),
                ('tipo_de_vacuo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_vacuo.tipodevacuo', verbose_name='Tipo de Vácuo')),
                ('unidade_de_saude_de_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades_de_saude.unidadedesaude', verbose_name='Unidade de Saúde de Origem')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
