# Generated by Django 5.1.5 on 2025-01-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='enfermeiro',
            new_name='responsavel',
        ),
    ]
