# Generated by Django 5.1.5 on 2025-01-28 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_especialidade_especialida_removid_441019_idx'),
        ('generos', '0001_initial'),
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('medidas_de_precaucao', '0003_medidadeprecaucao_medidas_de__removid_b9d74a_idx'),
        ('nacionalidades_etnias', '0003_nacionalidadeetnia_nacionalida_removid_d22a3c_idx'),
        ('pacientes', '0002_rename_enfermeiro_paciente_responsavel'),
        ('portas_de_entrada', '0003_portadeentrada_portas_de_e_removid_35bd1a_idx'),
        ('status_de_paciente', '0003_statusdepaciente_status_de_p_removid_3470d6_idx'),
        ('tipos_de_cirurgia', '0003_tipodecirurgia_tipos_de_ci_removid_914369_idx'),
        ('tipos_de_o2', '0003_tipodeo2_tipos_de_o2_removid_ec9dc7_idx'),
        ('tipos_de_vacuo', '0003_tipodevacuo_tipos_de_va_removid_6a4b9d_idx'),
        ('unidades_de_saude', '0003_unidadedesaude_unidades_de_removid_8832d8_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generos.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_social',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='problemas_durante_transferencias',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Problemas Durante Transferências'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_de_cirurgia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_cirurgia.tipodecirurgia', verbose_name='Tipo de Cirurgia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_de_o2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_o2.tipodeo2', verbose_name='Tipo de O2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_de_vacuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_vacuo.tipodevacuo', verbose_name='Tipo de Vácuo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='unidade_de_saude_de_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades_de_saude.unidadedesaude', verbose_name='Unidade de Saúde de Origem'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['removido_em'], name='pacientes_p_removid_868dad_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['data_de_internacao', 'removido_em'], name='pacientes_p_data_de_17e063_idx'),
        ),
    ]
