# Generated by Django 5.1.5 on 2025-01-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitos', '0004_leito_paciente'),
        ('pacientes', '0003_alter_paciente_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='leito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_leito', to='leitos.leito', verbose_name='Leito'),
        ),
    ]
