# Generated by Django 5.1.5 on 2025-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_leito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='hora_de_internacao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora_de_internacao_no_setor',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_de_internacao',
            field=models.DateTimeField(verbose_name='Data de Internação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_de_internacao_no_setor',
            field=models.DateTimeField(verbose_name='Data de Internação no Setor'),
        ),
    ]
