# Generated by Django 5.1.5 on 2025-01-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        ('setores', '0001_initial'),
        ('status_de_leito', '0001_initial'),
        ('tipos_de_leito', '0001_initial'),
        ('tipos_de_o2', '0001_initial'),
        ('tipos_de_vacuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sus', models.TextField(null=True, verbose_name='Código SUS')),
                ('tem_o2', models.BooleanField(default=False, verbose_name='Tem O2')),
                ('tem_vacuo', models.BooleanField(default=False, verbose_name='Tem Vácuo')),
                ('tem_codigo_sus', models.BooleanField(default=False, verbose_name='Tem Código SUS')),
                ('removido_em', models.DateTimeField(null=True, verbose_name='Removido em')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setores.setor', verbose_name='Setor')),
                ('status_de_leito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status_de_leito.statusdeleito', verbose_name='Status de Leito')),
                ('tipo_de_leito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_de_leito.tipodeleito', verbose_name='Tipo de Leito')),
                ('tipo_de_o2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_de_o2.tipodeo2', verbose_name='Tipo de O2')),
                ('tipo_de_vacuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos_de_vacuo.tipodevacuo', verbose_name='Tipo de Vácuo')),
            ],
            options={
                'verbose_name': 'Leito',
                'verbose_name_plural': 'Leitos',
            },
        ),
    ]
