# Generated by Django 5.1.5 on 2025-01-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitos', '0001_initial'),
        ('tipos_de_o2', '0002_alter_tipodeo2_removido_em'),
        ('tipos_de_vacuo', '0002_alter_tipodevacuo_removido_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='codigo_sus',
            field=models.TextField(blank=True, null=True, verbose_name='Código SUS'),
        ),
        migrations.AlterField(
            model_name='leito',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AlterField(
            model_name='leito',
            name='tipo_de_o2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_o2.tipodeo2', verbose_name='Tipo de O2'),
        ),
        migrations.AlterField(
            model_name='leito',
            name='tipo_de_vacuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipos_de_vacuo.tipodevacuo', verbose_name='Tipo de Vácuo'),
        ),
    ]
