# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_especialidade_especialida_removid_441019_idx'),
        ('leitos', '0002_alter_leito_codigo_sus_alter_leito_removido_em_and_more'),
        ('setores', '0003_setor_setores_set_removid_d33d62_idx'),
        ('status_de_leito', '0003_statusdeleito_status_de_l_removid_a0a760_idx'),
        ('tipos_de_leito', '0003_tipodeleito_tipos_de_le_removid_02bcab_idx'),
        ('tipos_de_o2', '0003_tipodeo2_tipos_de_o2_removid_ec9dc7_idx'),
        ('tipos_de_vacuo', '0003_tipodevacuo_tipos_de_va_removid_6a4b9d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leito',
            index=models.Index(fields=['removido_em'], name='leitos_leit_removid_576f57_idx'),
        ),
    ]
