# Generated by Django 5.1.5 on 2025-01-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('pacientes', '0003_alter_paciente_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leito_paciente', to='pacientes.paciente', verbose_name='Paciente'),
        ),
    ]
