# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitos', '0003_leito_leitos_leit_removid_576f57_idx'),
        ('pacientes', '0003_alter_paciente_data_de_nascimento_and_more'),
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['removido_em'], name='transferenc_removid_e5a759_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['data', 'removido_em'], name='transferenc_data_2378f0_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['paciente', 'removido_em'], name='transferenc_pacient_89aec5_idx'),
        ),
    ]
