# Generated by Django 5.1.5 on 2025-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0002_transferencia_transferenc_removid_e5a759_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
    ]
