# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_de_saude', '0002_alter_unidadedesaude_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='unidadedesaude',
            index=models.Index(fields=['removido_em'], name='unidades_de_removid_8832d8_idx'),
        ),
    ]
