# Generated by Django 5.1.5 on 2025-01-17 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status_de_usuario', '0001_initial'),
        ('tipos_de_usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_de_usuario', to='status_de_usuario.statusdeusuario', verbose_name='Status de Usuário')),
                ('tipo_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_de_usuario', to='tipos_de_usuario.tipodeusuario', verbose_name='Tipo de Usuário')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
