# Generated by Django 5.1.5 on 2025-01-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_de_usuario', '0001_initial'),
        ('usuarios', '0004_alter_usuario_status_de_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status_de_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='status_de_usuario', to='status_de_usuario.statusdeusuario', verbose_name='Status de Usuário'),
        ),
    ]
