# Generated by Django 5.1.5 on 2025-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas_de_entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadeentrada',
            name='removido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
    ]
