# Generated by Django 5.1.5 on 2025-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas_de_entrada', '0002_alter_portadeentrada_removido_em'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portadeentrada',
            index=models.Index(fields=['removido_em'], name='portas_de_e_removid_35bd1a_idx'),
        ),
    ]
